### ISSUE TITLE
Setup configuration documentation

### ISSUE THREAD

**Issue by ljenecker** [Swimming-Club-Data-Systems/Membership#22]
Unable to start launch project.

Errors (on startup):

Notice: Undefined variable: custom_domain_mode
Notice: Undefined variable: config
Notice: Undefined variable: cookie_prefix in 
Warning: require(): Filename cannot be empty
Fatal error: require(): Failed opening required '' (include_path='.:/usr/share/php') 

Steps taken:
1) Set up the SQL database tables using provided schema. 
2) Modify the config.php file to connect to database.
3) Run in local webserver.

I have tried removing custom_domain_mode and setting $config = 'config.php';

**Comment by clheppell** [comment]
This issue is due to setup documentation and the example config file provided not being up to date. Updated documentation, a new config file and a new schema will be made available soon.

**Comment by ljenecker** [comment]
Any chance that you had a look at this?
